### ISSUE TITLE
Just curious

### ISSUE THREAD

**Issue by anonimo82** [sjoerdev/voxel-engine#1]
@sjoerdev 
Just for curiosity, are the Voxel really stored in a 3D array?

I mean, a bitmap graphic is a 2D grid of pixels.
Is a model in your App a 3D grid of voxels?

Before answering, consider the difference between how does it appear on screen and how is it represented in memory.

Thanks for any help. Have a nice day.

**Comment by sjoerdev** [comment]
Hey there! 

Thanks for showing interest in my humble little engine ;)

This is how the voxels are represented in memory:
CPU side: 3d array of float's (the float represents the hue)
GPU side: 3d texture that holds a float in the R channel.
Disk side: The data is flattened into a single dimentional array and then serialized to either json or binary

I hope this answers your question. If not, you can find me on discord by this username: Sjoerd#5017

**Comment by anonimo82** [comment]
Yes, it's what I was looking for.
I'll add you ASAP on Discord
P.S.: Thanks for your help and your time

**Comment by anonimo82** [comment]
I'm idj
